# Generated by Django 2.0rc1 on 2017-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synopsis',
            field=models.CharField(default='', max_length=140),
        ),
    ]
