# Generated by Django 2.0rc1 on 2017-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviews',
            field=models.BigIntegerField(default=0),
        ),
    ]
